### PR TITLE
Update Cilium to 1.11.10

### PR DESCRIPTION
**Pull request by ysksuzuki**
This PR upgrade the Cilium image to 1.11.10

- Rebase the patch 18454. https://github.com/cilium/cilium/compare/v1.11.10...ysksuzuki:cilium:v1.11.10-with-18454
- Remove the patches 19936 and 20006
  - 19936 has been backported
  -  20006 is no longer needed. The stale ct issue has been fixed by the patch 18454

### CODE REVIEW

**Review by yokaze — COMMENTED** [review]
`maintenance.md` says we need to use the latest `cilium/image-tools`. Don't we need to update it?

**Comment by ysksuzuki** [comment]
Nice catch! Updated the image-tools hash

**Review by terassyi — APPROVED** [review]
LGTM

**Review by yokaze — APPROVED** [review]
LGTM

**Comment by ysksuzuki** [comment]
Thank you!

**Pull request merged**
