### PR TITLE
update kubernetes to 1.30.5

### PR DESCRIPTION
**Pull request by YZ775**

### CODE REVIEW

**Review by chez-shanpu — COMMENTED** [review]
Is it ok that 1.30.4 remains in `pause/Dockerfile` and `pod-delete-rate-limiter/Makefile`?

**Comment by YZ775** [comment]
@chez-shanpu 
Thank you for reviewing,

There are no diff between 1.30.4 and 1.30.5, I think we don't need to update pause.
https://github.com/kubernetes/kubernetes/tree/v1.30.4/build/pause
https://github.com/kubernetes/kubernetes/tree/v1.30.5/build/pause

In addition, `ENVTEST_K8S_VERSION` in `pod-delete-rate-limiter/Makefile` is only used for test. So I think we don't need to update.

**Comment by chez-shanpu** [comment]
@YZ775 I see. As you say,  they don't seem to need updating.
I'll approve it :)

**Review by chez-shanpu — APPROVED** [review]
LGTM

**Comment by YZ775** [comment]
Thank you!

**Pull request merged**
