### PR TITLE
admission: update for k8s 1.25 and Go 1.19 

### PR DESCRIPTION
**Pull request by zeroalphat**
- Update go.mod
Signed-off-by: zeroalphat <taichi-takemura@cybozu.co.jp>

### CODE REVIEW

**Review by yokaze — CHANGES_REQUESTED** [review]
Please check the followings.

- Update the official Go modules to `v0.25.6`.
- Update `sigs.k8s.io/controller-runtime` to v0.13.1, which is compatible with k8s 1.25.

**Comment by zeroalphat** [comment]
I would like to know for future work, how is it determined that this version is an official module?
> * Update the official Go modules to `v0.25.6`.

**Comment by yokaze** [comment]
@zeroalphat 
I suspect `k8s.io/api`, `k8s.io/apimachinery`, and `k8s.io/client-go` are maintained officially by the k8s' maintainers.
`k8s.io/api@v0.25.6` stands for k8s 1.25.6.

**Review by yokaze — APPROVED** [review]
LGTM

**Pull request merged**
