### PR TITLE
upgrade golang to 1.17.1

### PR DESCRIPTION
**Pull request by umezawatakeshi**
Signed-off-by: UMEZAWA Takeshi <takeshi-umezawa@cybozu.co.jp>

### CODE REVIEW

**Review by yokaze — CHANGES_REQUESTED** [review]
I think these two files should be updated.
- `golang/analyzer/go.mod`
- `golang-bionic/analyzer/go.mod`

**Comment by umezawatakeshi** [comment]
@yokaze 
It is already done in https://github.com/cybozu/neco-containers/pull/649

**Comment by yokaze** [comment]
@umezawatakeshi Go version in the `go.mod` is still go 1.16. Is it OK?

**Comment by umezawatakeshi** [comment]
@yokaze oops

**Comment by umezawatakeshi** [comment]
I wonder that `go mod tidy` did not do so.

**Comment by morimoto-cybozu** [comment]
@yokaze @umezawatakeshi 
FYI

https://golang.org/doc/go1.17#graph-pruning
> Because the number of explicit requirements may be substantially larger in an expanded Go 1.17 `go.mod` file, the newly-added requirements on _indirect_ dependencies in a `go 1.17` module are maintained in a separate `require` block from the block containing direct dependencies.

https://golang.org/issue/45965

**Pull request merged**
