### PR TITLE
Update go to 1.17.8 and 1.16.15

### PR DESCRIPTION
**Pull request by masa213f**
Signed-off-by: Masayuki Ishii <masa213f@gmail.com>

### CODE REVIEW

**Review by yokaze — CHANGES_REQUESTED** [review]
It seems `go mod tidy` would remove some dependencies.

**Comment by masa213f** [comment]
@yokaze 
Thank you. I will check `go mod tidy` in CI.
https://github.com/cybozu/neco-containers/pull/764

**Comment by masa213f** [comment]
rebased and `go mod tidy`

**Review by yokaze — APPROVED** [review]
LGTM

**Pull request merged**
